version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./start.sh:/var/www/start.sh
    environment:
      CONTAINER_TYPE: app
    entrypoint: ["sh", "start.sh"]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
  scheduler-worker:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./start.sh:/var/www/start.sh
    environment:
      CONTAINER_TYPE: scheduler
    entrypoint: ["sh", "start.sh"]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
  dividend-worker:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./start.sh:/var/www/start.sh
    environment:
      CONTAINER_TYPE: dividend
    entrypoint: ["sh", "start.sh"]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
  emails-worker:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./start.sh:/var/www/start.sh
    environment:
      CONTAINER_TYPE: emails
    entrypoint: ["sh", "start.sh"]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
  simulation-worker:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./start.sh:/var/www/start.sh
    environment:
      CONTAINER_TYPE: simulation
    entrypoint: ["sh", "start.sh"]
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
  websocket:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./start.sh:/var/www/start.sh
    environment:
      CONTAINER_TYPE: websocket
    entrypoint: ["sh", "start.sh"]
    depends_on:
      - php
      - redis
    networks:
      - app-network
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app-network
  laravel-echo-server:
    build:
      context: ./laravel-echo-server
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "6001:6001"
    depends_on:
      - redis
    networks:
      - app-network
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/.ssh:/ssh
    depends_on:
      - php
      - node
    networks:
      - app-network
  redis:
    image: redis:latest
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - app-network
  mysql:
    image: mysql:8.0.35
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
