version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./php/app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app-network
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
      - node
    networks:
      - app-network
  redis:
    image: redis:latest
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - app-network
  mysql:
    image: mysql:8.0.35
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
